name: coast_audio
description: A cross-platform audio processing library written in dart
version: 0.1.0
repository: https://github.com/SKKbySSK/coast_audio/tree/main/packages/coast_audio

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  disposing: ^1.0.3+1
  build_runner: ^2.4.8
  meta: ^1.12.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.4.4
  coverage: ^1.7.2
