// Mocks generated by Mockito 5.4.4 from annotations
// in coast_audio/test/node/mixin/processor_node_mixin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ffi' as _i3;

import 'package:coast_audio/coast_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'processor_node_mixin_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioFormat_0 extends _i1.SmartFake implements _i2.AudioFormat {
  _FakeAudioFormat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemory_1 extends _i1.SmartFake implements _i2.Memory {
  _FakeMemory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioBuffer_2 extends _i1.SmartFake implements _i2.AudioBuffer {
  _FakeAudioBuffer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioNode_3 extends _i1.SmartFake implements _i2.AudioNode {
  _FakeAudioNode_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioReadResult_4 extends _i1.SmartFake
    implements _i2.AudioReadResult {
  _FakeAudioReadResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioBuffer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioBuffer extends _i1.Mock implements _i2.AudioBuffer {
  MockAudioBuffer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Pointer<_i3.Uint8> get pBuffer => (super.noSuchMethod(
        Invocation.getter(#pBuffer),
        returnValue: _i4.dummyValue<_i3.Pointer<_i3.Uint8>>(
          this,
          Invocation.getter(#pBuffer),
        ),
      ) as _i3.Pointer<_i3.Uint8>);

  @override
  int get sizeInBytes => (super.noSuchMethod(
        Invocation.getter(#sizeInBytes),
        returnValue: 0,
      ) as int);

  @override
  int get sizeInFrames => (super.noSuchMethod(
        Invocation.getter(#sizeInFrames),
        returnValue: 0,
      ) as int);

  @override
  _i2.AudioFormat get format => (super.noSuchMethod(
        Invocation.getter(#format),
        returnValue: _FakeAudioFormat_0(
          this,
          Invocation.getter(#format),
        ),
      ) as _i2.AudioFormat);

  @override
  _i2.Memory get memory => (super.noSuchMethod(
        Invocation.getter(#memory),
        returnValue: _FakeMemory_1(
          this,
          Invocation.getter(#memory),
        ),
      ) as _i2.Memory);

  @override
  _i2.AudioBuffer offset(int? frames) => (super.noSuchMethod(
        Invocation.method(
          #offset,
          [frames],
        ),
        returnValue: _FakeAudioBuffer_2(
          this,
          Invocation.method(
            #offset,
            [frames],
          ),
        ),
      ) as _i2.AudioBuffer);

  @override
  _i2.AudioBuffer limit(int? frames) => (super.noSuchMethod(
        Invocation.method(
          #limit,
          [frames],
        ),
        returnValue: _FakeAudioBuffer_2(
          this,
          Invocation.method(
            #limit,
            [frames],
          ),
        ),
      ) as _i2.AudioBuffer);
}

/// A class which mocks [AudioInputBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioInputBus extends _i1.Mock implements _i2.AudioInputBus {
  MockAudioInputBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioNode get node => (super.noSuchMethod(
        Invocation.getter(#node),
        returnValue: _FakeAudioNode_3(
          this,
          Invocation.getter(#node),
        ),
      ) as _i2.AudioNode);

  @override
  void onConnect(_i2.AudioOutputBus? bus) => super.noSuchMethod(
        Invocation.method(
          #onConnect,
          [bus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDisconnect() => super.noSuchMethod(
        Invocation.method(
          #onDisconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioOutputBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioOutputBus extends _i1.Mock implements _i2.AudioOutputBus {
  MockAudioOutputBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioNode get node => (super.noSuchMethod(
        Invocation.getter(#node),
        returnValue: _FakeAudioNode_3(
          this,
          Invocation.getter(#node),
        ),
      ) as _i2.AudioNode);

  @override
  void onConnect(_i2.AudioInputBus? bus) => super.noSuchMethod(
        Invocation.method(
          #onConnect,
          [bus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDisconnect() => super.noSuchMethod(
        Invocation.method(
          #onDisconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AudioReadResult read(_i2.AudioBuffer? buffer) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [buffer],
        ),
        returnValue: _FakeAudioReadResult_4(
          this,
          Invocation.method(
            #read,
            [buffer],
          ),
        ),
      ) as _i2.AudioReadResult);
}

/// A class which mocks [AudioProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProcessor extends _i1.Mock implements _i5.AudioProcessor {
  MockAudioProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioReadResult process(
    _i2.AudioBuffer? buffer,
    bool? isEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #process,
          [
            buffer,
            isEnd,
          ],
        ),
        returnValue: _FakeAudioReadResult_4(
          this,
          Invocation.method(
            #process,
            [
              buffer,
              isEnd,
            ],
          ),
        ),
      ) as _i2.AudioReadResult);
}
