build_apple:
	@rm -rf build
	@./scripts/apple_build.sh
	@fvm dart run scripts/symbol_keeper.dart

build_android:
	@rm -rf build
	@./scripts/android_build.sh

build_linux:
	@rm -rf build
	@./scripts/linux_build.sh