// Mocks generated by Mockito 5.4.4 from annotations
// in coast_audio/test/node/decoder_node_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:coast_audio/coast_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioFormat_0 extends _i1.SmartFake implements _i2.AudioFormat {
  _FakeAudioFormat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioDecodeResult_1 extends _i1.SmartFake
    implements _i2.AudioDecodeResult {
  _FakeAudioDecodeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioDecoder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioDecoder extends _i1.Mock implements _i2.AudioDecoder {
  MockAudioDecoder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioFormat get outputFormat => (super.noSuchMethod(
        Invocation.getter(#outputFormat),
        returnValue: _FakeAudioFormat_0(
          this,
          Invocation.getter(#outputFormat),
        ),
      ) as _i2.AudioFormat);

  @override
  int get cursorInFrames => (super.noSuchMethod(
        Invocation.getter(#cursorInFrames),
        returnValue: 0,
      ) as int);

  @override
  set cursorInFrames(int? value) => super.noSuchMethod(
        Invocation.setter(
          #cursorInFrames,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get canSeek => (super.noSuchMethod(
        Invocation.getter(#canSeek),
        returnValue: false,
      ) as bool);

  @override
  _i2.AudioDecodeResult decode({required _i2.AudioBuffer? destination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #decode,
          [],
          {#destination: destination},
        ),
        returnValue: _FakeAudioDecodeResult_1(
          this,
          Invocation.method(
            #decode,
            [],
            {#destination: destination},
          ),
        ),
      ) as _i2.AudioDecodeResult);
}
